# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-04 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190704_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
