# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20190704_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='external_odoo_record_num',
            field=models.IntegerField(default=0),
        ),
    ]
